###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################

module(
    name = "xibalba",
    version = "0.1.0",
)

# Rules for building OCI (Docker) images - used for hermetic build environment
bazel_dep(name = "rules_oci", version = "1.7.4")

# Pull Ubuntu base image for build tools container
oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "ubuntu_base",
    image = "ubuntu",
    tag = "24.04",
    platforms = ["linux/amd64"],  # We're targeting x86-64
    # TODO: Pin digest once we verify this works
)
use_repo(oci, "ubuntu_base")
